# Site settings
title: Pushpendre Rastogi
email: pushpendre@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web page of Pushpendre Rastogi
baseurl: "/~prastog3" # the subpath of your site, e.g. /blog/
url: "http://cs.jhu.edu/~prastog3"
github_username:  se4u
# Build settings
markdown: kramdown
lsi: false
defaults:

  scope:
    path: ""
  values:
    layout: "default"

  # scope:
  #   path: "projects"
  # values:
  #   layout: "project"
