# Site settings
title: Pushpendre Rastogi
email: pushpendre@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web page of Pushpendre Rastogi
baseurl: "/~prastog3" # the subpath of your site, e.g. /blog/
url: "http://cs.jhu.edu/~prastog3"
github_username:  se4u
# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

lsi: false
include: ["_includes", "mtp.pdf", "_static"]
exclude: ["Makefile", "_includes/*.*"] # Why is this here?
gems: ['jekyll/footnotes', 'jekyll/scholar']
defaults:

  scope:
    path: ""
  values:
    layout: "default"